name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master
      - QA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'  

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build MaquinaDeCafeApp.sln --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test MaquinaDeCafeTest --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/QA'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Deploy to Dev Environment
        if: github.ref == 'refs/heads/dev'
        run: echo "Desplegando en el entorno de desarrollo..."

      - name: Deploy to QA Environment
        if: github.ref == 'refs/heads/QA'
        run: echo "Desplegando en el entorno QA..."

      - name: Deploy to Production Environment
        if: github.ref == 'refs/heads/master'
        run: echo "Desplegando en el entorno de producción..."
